### PR TITLE
Set up coffee-script as a dev dependency, build on prepublish.

### PR DESCRIPTION
**Pull request by timoxley**
Builds coffee `./src` into js `./lib` at prepublish time, removes runtime dependency on coffee-script.

coffee-script's `require('coffee-script/register')` conflicts with other tools, should be avoided at runtime.

Existing tests don't seem to run for me, even using totally unmodified code, but code seems to work in my app.

See https://docs.npmjs.com/misc/scripts#common-uses

### CODE REVIEW

**Comment by gevorg** [comment]
Thanks a lot!

**Comment by Slayer95** [comment]
@timoxley, if you could send a similar PR to gevorg/htpasswd (it's a dependency of `http-auth`) it would be awesome :)

Then I could ditch my after-compile forks of the projects.

**Comment by gevorg** [comment]
@Slayer95 just did it.

**Comment by Slayer95** [comment]
Great!

**Pull request merged**
